### ISSUE TITLE
Does not work on Rails edge

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#924]
Bisected to: https://github.com/rails/rails/commit/c477d95604e80e04d1aa8113a8236353235eb86a

rails/rails#43223

### Steps to reproduce*
https://github.com/DavyJonesLocker/client_side_validations/actions/runs/6623856813/job/17991682062

### Expected behavior*
Work

### Actual behavior*
```
rails/activerecord/lib/active_record/validations/uniqueness.rb:287:in `validates_uniqueness_of': undefined method `_merge_attributes' for UserForm:Class (NoMethodError)

        validates_with UniquenessValidator, _merge_attributes(attr_names)
	from ~/dev/client_side_validations/test/active_record/models/user.rb:25:in `<class:UserForm>'
	from ~/dev/client_side_validations/test/active_record/models/user.rb:20:in `<top (required)>'
```

### System configuration*
**Rails version**: edge 

**Ruby version**: n/a

**Client Side Validations version**: edge

### Code snippet from your model of the validations*
n/a

### The whole form code from your template*
n/a

### The resulting HTML*
n/a

### Browser's development console output*
- [x] I confirm that my browser's development console output does not contain errors

### Additional JavaScript Libraries*
n/a

### Repository demostrating the issue
Debugging CSV issues is a time consuming task. If you want to speed up things, please
provide a link to a repository showing the issue.

---

**\*** Failure to include this requirement may result in the issue being closed.
