### ISSUE TITLE
Specs broken against Rails 7.2.2

### ISSUE THREAD

**Issue by tagliala** [DavyJonesLocker/client_side_validations#953]
### Steps to reproduce*

https://github.com/DavyJonesLocker/client_side_validations/actions/runs/11739315324/job/32703578245

### Expected behavior*
Work

### Actual behavior*

```
Error:
ActiveRecord::UniquenessValidatorTest#test_uniqueness_client_side_hash_with_empty_scope_array:
NoMethodError: undefined method `singleton_class?' for nil:NilClass
    vendor/bundle/ruby/3.2.0/gems/activerecord-7.2.2/lib/active_record/validations/uniqueness.rb:17:in `initialize'
    test/active_record/cases/test_uniqueness_validator.rb:71:in `new'
    test/active_record/cases/test_uniqueness_validator.rb:71:in `test_uniqueness_client_side_hash_with_empty_scope_array'

bin/rails test active_record/cases/test_uniqueness_validator.rb:69
```

### System configuration*
**Rails version**: 7.2.2

**Ruby version**: 3.x

**Client Side Validations version**: main

### Code snippet from your model of the validations*
n/a

### The whole form code from your template*
n/a

### The resulting HTML*
n/a

### Browser's development console output*
- [x] I confirm that my browser's development console output does not contain errors

### Additional JavaScript Libraries*
n/a

### Repository demostrating the issue
this repo

**Comment by tagliala** [comment]
Bisected to rails/rails@64a64fd548a1d7bcb349d0a56855994e10e398dd

**Comment by tagliala** [comment]
Fixed in #952
