### ISSUE TITLE
uniqueness validator throws NoMethodError exception

### ISSUE THREAD

**Issue by derekatkins** [DavyJonesLocker/client_side_validations#415]
I'm working with c_s_v 3.2.0 with rails 3.1.3 and I've noticed the following entries in my log when trying to update an existing object:

<pre>
Started GET "/validators/uniqueness?case_sensitive=true&id=76b2a4d4-6b7d-4e7f-8a93-d07865225618&company%5Bname%5D=Test" for 127.0.0.1 at Thu Oct 18 16:40:21 -0400 2012

NoMethodError (undefined method `not_eq' for nil:NilClass):
  

Rendered /home/warlord/.rvm/gems/ruby-1.8.7-p370@sdm/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/_trace.erb (0.8ms)
Rendered /home/warlord/.rvm/gems/ruby-1.8.7-p370@sdm/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.6ms)
Rendered /home/warlord/.rvm/gems/ruby-1.8.7-p370@sdm/gems/actionpack-3.1.3/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (2.7ms)
</pre>

For kicks I went off and ran this GET my hand to try to get a full stack trace:

<pre>
activesupport (3.1.3) lib/active_support/whiny_nil.rb:48:in `method_missing'
client_side_validations (3.2.0) lib/client_side_validations/active_record/middleware.rb:29:in `is_unique?'
client_side_validations (3.2.0) lib/client_side_validations/middleware.rb:100:in `is_unique?'
client_side_validations (3.2.0) lib/client_side_validations/middleware.rb:53:in `response'
client_side_validations (3.2.0) lib/client_side_validations/middleware.rb:18:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.3.6) lib/rack/etag.rb:23:in `call'
rack (1.3.6) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/flash.rb:247:in `call'
rack (1.3.6) lib/rack/session/abstract/id.rb:195:in `context'
rack (1.3.6) lib/rack/session/abstract/id.rb:190:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/cookies.rb:331:in `call'
activerecord (3.1.3) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.1.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:477:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/callbacks.rb:29:in `call'
activesupport (3.1.3) lib/active_support/callbacks.rb:392:in `_run_call_callbacks'
activesupport (3.1.3) lib/active_support/callbacks.rb:81:in `send'
activesupport (3.1.3) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.1.3) lib/action_dispatch/middleware/callbacks.rb:28:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/reloader.rb:68:in `call'
rack (1.3.6) lib/rack/sendfile.rb:101:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/remote_ip.rb:48:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/show_exceptions.rb:47:in `call'
railties (3.1.3) lib/rails/rack/logger.rb:13:in `call'
rack (1.3.6) lib/rack/methodoverride.rb:24:in `call'
rack (1.3.6) lib/rack/runtime.rb:17:in `call'
activesupport (3.1.3) lib/active_support/cache/strategy/local_cache.rb:72:in `call'
rack (1.3.6) lib/rack/lock.rb:15:in `call'
actionpack (3.1.3) lib/action_dispatch/middleware/static.rb:53:in `call'
railties (3.1.3) lib/rails/engine.rb:456:in `call'
railties (3.1.3) lib/rails/railtie/configurable.rb:30:in `send'
railties (3.1.3) lib/rails/railtie/configurable.rb:30:in `method_missing'
rack (1.3.6) lib/rack/deflater.rb:13:in `call'
rack (1.3.6) lib/rack/content_length.rb:14:in `call'
railties (3.1.3) lib/rails/rack/log_tailer.rb:14:in `call'
rack (1.3.6) lib/rack/handler/webrick.rb:59:in `service'
/home/warlord/.rvm/rubies/ruby-1.8.7-p370/lib/ruby/1.8/webrick/httpserver.rb:104:in `service'
[snip]
</pre>

I would've just turned off the uniqueness validations completely but the documentation is wrong, under the Security section it says I can disable the uniqueness validator via ClientSideValidations::Config.uniqueness_validator_disabled = true but of course that was removed in 3.2.0 (c.f. Issue #400) but the docs have not been updated to reflect the new way to handle that.
